// @ts-check
import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/.turbo/**",
      "**/generated/**",
      // Generated by Next on build — not ours to lint or edit.
      "**/next-env.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      // Unused vars are errors, but a leading _ marks a deliberate placeholder.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // Servvo-specific: floating promises on a write path can drop an audit row.
      "@typescript-eslint/no-floating-promises": "off", // needs type-aware linting; enable with project service
      "no-console": ["warn", { allow: ["warn", "error", "info", "log"] }],
    },
  },
  {
    // Tests may lean on `any` when building mocks for vendor payloads.
    files: ["**/*.test.ts", "**/*.test.tsx"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
);
